// src/constants/productsData.js

export const categories = [
  { id: "rau-cu", title: "Rau củ quả", img: "/image/cart/anh1.png" },
  { id: "thit-ca", title: "Thịt, cá, hải sản", img: "/image/cart/anh2.png" },
  { id: "trai-cay", title: "Trái cây", img: "/image/cart/anh3.png" },
  { id: "sua-trung", title: "Sữa & Trứng", img: "/image/cart/anh4.png" },
  { id: "do-uong", title: "Đồ uống", img: "/image/cart/anh5.png" },
  { id: "an-nhanh", title: "Đồ ăn nhanh", img: "/image/cart/anh6.png" },
  { id: "banh-keo", title: "Bánh & Kẹo", img: "/image/cart/banhkeo.png"},
  {id: "ngu-coc", title: "Ngũ cốc dinh dưỡng", img: "/image/cart/ngucoc.png"},

]

export const allProducts = [
  // ================= 1. NHÓM RAU CỦ QUẢ =================
  { id: 101, category: "rau-cu", title: "Bông cải xanh Đà Lạt", price: 35000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/anh8.png" },
  { id: 102, category: "rau-cu", title: "Xà lách thủy canh mỡ", price: 25000, oldPrice: 30000, discount: "-16%", rating: 4.8, img: "/image/cart/xalach.png" },
  { id: 103, category: "rau-cu", title: "Cà chua cherry organic", price: 42000, oldPrice: 50000, discount: "-16%", rating: 4.9, img: "/image/cart/cachua.png" },
  { id: 104, category: "rau-cu", title: "Bắp cải tím", price: 18000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/bapcai.png" },
  { id: 105, category: "rau-cu", title: "Cà rốt Đà Lạt tươi", price: 22000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/carot.png" },
  { id: 106, category: "rau-cu", title: "Khoai tây sạch", price: 28000, oldPrice: 32000, discount: "-12%", rating: 4.5, img: "/image/cart/khoaitay.png" },
  { id: 107, category: "rau-cu", title: "Rau muống tươi", price: 15000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/rau.png" },
  { id: 108, category: "rau-cu", title: "Ớt chuông đủ màu", price: 30000, oldPrice: 40000, discount: "-25%", rating: 4.8, img: "/image/cart/ot.png" },
  { id: 109, category: "rau-cu", title: "Hành tây Đà Lạt", price: 20000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/hanhtay.png" },
  { id: 110, category: "rau-cu", title: "Cải bó xôi tươi", price: 25000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/caiboxoi.png" },
  { id: 111, category: "rau-cu", title: "Dưa leo sạch", price: 18000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/dualeo.png" },
  { id: 112, category: "rau-cu", title: "Củ cải trắng", price: 20000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/cucai.png" },
  { id: 113, category: "rau-cu", title: "Rau mồng tơi", price: 10000, oldPrice:null, discount:null, rating:5.0, img: "/image/cart/mongtoi.png"},
  { id: 114, category: "rau-cu", title: "Bí đao", price: 17000, ordPrice: null, discount:null, rating: 4.5, img: "/image/cart/bidao.png"},
  { id: 115, category: "rau-cu", title: "Bắp ngô ngọt <1 kg>", price:10000, ordPrice:null, discount: null, rating: 4.0, img: "/image/cart/ngo.png"},
  // ================= 2. NHÓM THỊT, CÁ, HẢI SẢN =================
  { id: 201, category: "thit-ca", title: "Cá hồi phi lê Nauy", price: 185000, oldPrice: 210000, discount: "HOT", rating: 5.0, img: "/image/cart/anh9.png" },
  { id: 202, category: "thit-ca", title: "Thịt bò Mỹ ba chỉ", price: 185000, oldPrice: 210000, discount: "HOT", rating: 5.0, img: "/image/cart/bomi.png" },
  { id: 203, category: "thit-ca", title: "Ức gà", price: 65000, oldPrice: 75000, discount: "-13%", rating: 4.8, img: "/image/cart/ucga.png" },
  { id: 204, category: "thit-ca", title: "Tôm sú biển", price: 320000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/tom.png" },
  { id: 205, category: "thit-ca", title: "Thịt heo", price: 160000, oldPrice: 180000, discount: "-11%", rating: 4.7, img: "/image/cart/thit.png" },
  { id: 206, category: "thit-ca", title: "Thịt vịt", price: 250000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/thịt vịt.png" },
  { id: 207, category: "thit-ca", title: "Cá thu một nắng", price: 120000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/cathu.png" },
  { id: 208, category: "thit-ca", title: "Mực tươi nguyên con", price: 200000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/muc.png" },
  { id: 209, category: "thit-ca", title: "Thịt cừu New Zealand", price: 350000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/cuu.png" },
  { id: 210, category: "thit-ca", title: "Cá basa phi lê", price: 90000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/basa.png" },
  { id: 211, category: "thit-ca", title: "Thịt gà ta", price: 120000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/ga.png" },
  { id: 212, category: "thit-ca", title: "Cá trê", price: 80000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/catre.png" },
  { id: 213, category: "thit-ca", title: "Cá rô đồng <1 kg>", price: 90000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/caro.png" },
  { id: 214, category: "thit-ca", title: "Tôm hùm", price: 500000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/tomhum.png" },
  { id: 215, category: "thit-ca", title: "Cá nục biển", price: 150000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/canuc.png" },
  // ================= 3. NHÓM TRÁI CÂY =================
  { id: 301, category: "trai-cay", title: "Táo đỏ nhập khẩu", price: 85000, oldPrice: 185000, discount: "HOT", rating: 4.9, img: "/image/cart/anh7.png" },
  { id: 302, category: "trai-cay", title: "Mận hậu Sơn La ngọt", price: 45000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/anh11.png" },
  { id: 303, category: "trai-cay", title: "Xoài cát Hòa Lộc loại 1", price: 75000, oldPrice: 90000, discount: "-16%", rating: 4.8, img: "/image/cart/xoai.png" },
  { id: 304, category: "trai-cay", title: "Bơ sáp Đắk Lắk", price: 50000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/bo.png" },
  { id: 305, category: "trai-cay", title: "Cam sành Hàm Yên", price: 25000, oldPrice: 35000, discount: "-28%", rating: 4.5, img: "/image/cart/cam.png" },
  { id: 306, category: "trai-cay", title: "Dưa hấu ruột đỏ", price: 30000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/dua.png" },
  { id: 307, category: "trai-cay", title: "Nho xanh không hạt", price: 60000, oldPrice: 80000, discount: "-25%", rating: 4.8, img: "/image/cart/nho.png" },
  { id: 308, category: "trai-cay", title: "Dứa thơm Queen", price: 20000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/dia.png" },
  { id: 309, category: "trai-cay", title: "Lê Hàn Quốc", price: 40000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/le.png" },
  { id: 310, category: "trai-cay", title: "Chuối sứ Lâm Đồng", price: 15000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/chuoi.png" },
  { id: 311, category: "trai-cay", title: "Mít Thái siêu ngọt", price: 35000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/mit.png" },
  { id: 312, category: "trai-cay", title: "Sầu riêng Ri6", price: 120000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/sau.png" },
  { id: 313, category: "trai-cay", title: "Vải thiều Lục Ngạn", price: 50000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/vai.png" },
  { id: 314, category: "trai-cay", title: "Dâu tây Đà Lạt", price: 60000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/dautay.png" },
  { id: 315, category: "trai-cay", title: "Bưởi ruột đỏ", price: 40000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/buoi.png" },

  // ================= 4. NHÓM SỮA & TRỨNG =================
  { id: 401, category: "sua-trung", title: "Sữa tươi Vinamilk 1L", price: 28000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/anh10.png" },
  { id: 402, category: "sua-trung", title: "Trứng gà ta (Hộp 10 quả)", price: 35000, oldPrice: 40000, discount: "-12%", rating: 4.8, img: "/image/cart/trungga.png" },
  { id: 403, category: "sua-trung", title: "Sữa chua nếp cẩm Ba Vì", price: 8000, oldPrice: 10000, discount: "-20%", rating: 4.0, img: "/image/cart/nepcam.png" },
  { id: 404, category: "sua-trung", title: "Phô mai con bò cười", price: 45000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/conbocuoi.png" },
  { id: 405, category: "sua-trung", title: "Trứng vịt lộn (Hộp 10 quả)", price: 50000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/trungvit.png" },
  { id: 406, category: "sua-trung", title: "Sữa đặc ngôi sao Phương Nam", price: 45000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/suadac.png" },
  { id: 407, category: "sua-trung", title: "TH true milk (1 thùng)", price: 300000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/TH.png" },
  { id: 408, category: "sua-trung", title: "Trứng cút (Hộp 20 quả)", price: 20000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/trungcut.png" },
  { id: 409, category: "sua-trung", title: "Sữa chua uống Yakult", price: 30000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/yakult.png" },
  { id: 410, category: "sua-trung", title: "Sữa tươi organic", price: 35000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/sua.png" },
  { id: 411, category: "sua-trung", title: "Sữa tiệt trùng Mộc Châu", price: 100000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/mocchau.png" },
  { id: 412, category: "sua-trung", title: "Sữa đậu nành Fami", price: 20000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/dau.png" },
  { id: 413, category: "sua-trung", title: "Sữa chua vi sinh", price: 15000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/chuasinh.png" },
  { id: 414, category: "sua-trung", title: "Sữa Ensure", price: 450000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/ensure.png" },
  { id: 415, category: "sua-trung", title: "Sữa ông Thọ <1 thùng>", price: 200000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/ongtho.png" },
  // ================= 5. NHÓM ĐỒ UỐNG =================
  { id: 501, category: "do-uong", title: "Nước ép cam nguyên chất", price: 32000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/nuoccam.png" },
  { id: 502, category: "do-uong", title: "Trà sữa truyền thống", price: 35000, oldPrice: 45000, discount: "-22%", rating: 4.7, img: "/image/cart/trasua.png" },
  { id: 503, category: "do-uong", title: "Nước khoáng Aquafina", price: 6000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/nuoc.png" },
  { id: 504, category: "do-uong", title: "Coca Cola lon 320ml", price: 11000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/coca.png" },
  { id: 505, category: "do-uong", title: "Trà xanh không độ", price: 15000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/tra.png" },
  { id: 506, category: "do-uong", title: "Nước ép dưa hấu", price: 30000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/nuocdua.png" },
  { id: 507, category: "do-uong", title: "Cà phê sữa Highlands", price: 20000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/highlands.png" },
  { id: 508, category: "do-uong", title: "Nước ép cà rốt", price: 30000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/nuoccarot.png" },
  { id: 509, category: "do-uong", title: "Trà đào cam sả", price: 35000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/tradao.png" },
  { id: 510, category: "do-uong", title: "Nước ép táo xanh", price: 30000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/nuoctao.png" },
  { id: 511, category: "do-uong", title: "Sữa chua uống vị dâu", price: 25000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/suadau.png" },
  { id: 512, category: "do-uong", title: "Trà chanh", price: 15000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/trachanh.png" },
  { id: 513, category: "do-uong", title: "Pepsi không calo lon 320ml", price: 11000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/pepsi.png" },
  { id: 514, category: "do-uong", title: "Nước ép dứa", price: 30000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/nuocdia.png" },
  { id: 515, category: "do-uong", title: "Trà chanh leo", price: 40000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/chanhleo.png" },

// ================= 6. NHÓM ĐỒ ĂN NHANH =================
  { id: 601, category: "an-nhanh", title: "Burger gà nướng BBQ", price: 55000, oldPrice: 65000, discount: "-15%", rating: 4.6, img: "/image/cart/burger.png" },
  { id: 602, category: "an-nhanh", title: "Khoai tây chiên", price: 29000, oldPrice: 35000, discount: "-17%", rating: 4.5, img: "/image/cart/chien.png" },
  { id: 603, category: "an-nhanh", title: "Đùi gà rán KFC (1 miếng)", price: 39000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/dui.png" },
  { id: 604, category: "an-nhanh", title: "Pizza hải sản cỡ vừa", price: 119000, oldPrice: 159000, discount: "HOT", rating: 4.7, img: "/image/cart/pizza.png" },
  { id: 605, category: "an-nhanh", title: "Mì xào hải sản", price: 59000, oldPrice: 79000, discount: "-25%", rating: 4.6, img: "/image/cart/mi.png" },
  { id: 606, category: "an-nhanh", title: "Gà rán KFC (Combo 2 người)", price: 119000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/KFC.png" },
  { id: 607, category: "an-nhanh", title: "Bánh mì thịt nướng", price: 25000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/banhmi.png" },
  { id: 608, category: "an-nhanh", title: "Xúc xích Đức", price: 45000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/xucxich.png" },
  { id: 609, category: "an-nhanh", title: "Bánh mì chảo", price: 35000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/banhmichao.png" },
  { id: 610, category: "an-nhanh", title: "Phở bò", price: 15000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/phobo.png" },
  { id: 611, category: "an-nhanh", title: "Bánh mì que", price: 20000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/banhmique.png" },
  { id: 612, category: "an-nhanh", title: "Gà rán Popeyes (Combo 2 người)", price: 129000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/popeyes.png" },
  { id: 613, category: "an-nhanh", title: "Bún chả Hà Nội", price: 30000, oldPrice: null, discount: null, rating: 4.5, img: "/image/cart/buncha.png" },
  { id: 614, category: "an-nhanh", title: "Nem nướng Nha Trang", price: 40000, oldPrice: null, discount: null, rating: 4.6, img: "/image/cart/nemnuong.png" },
  { id: 615, category: "an-nhanh", title: "Bún bò Huế", price: 45000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/bunbohue.png" },
  
  // ================= 7. NHÓM BÁNH KẸO =================
  { id: 701, category: "banh-keo", title: "Bánh Chocopie", price: 40000, oldPrice: null, discount: null, rating: 3, img: "/image/cart/chocopie.png"},
  { id: 702, category: "banh-keo", title: "Bánh đậu xanh Hòa An", price: 100000, oldPrice: null, discount: null, rating: 4.9, img:"/image/cart/banhdauxanh.png"},
  { id: 703, category: "banh-keo", title: "Bánh cáy Thái Bình", price: 60000, oldPrice: null, discount: null, rating: 4.8, img: "/image/cart/banhcay.png"},
  { id: 704, category: "banh-keo", title: "Kẹo dẻo cầu vòng Chupa Chups", price: 100000, oldPrice: null, discount: null, rating: 4.7, img: "/image/cart/keodeo.png"},
  { id: 705, category: "banh-keo", title: "Oishi", price: 6000, oldPrice: null, discount: null, rating: 4.3, img: "/image/cart/oishi.png"},
  { id: 706, category: "banh-keo", title: "Kẹo  Alpenliebe dâu", price: 15000, oldPrice: null, discount: "-5%", rating: 4.2, img: "/image/cart/alpenliebe.png"},
  { id: 707, category: "banh-keo", title: "Kẹo  Alpenliebe muối ớt", price: 15000, oldPrice: null, discount: null, rating: 4.2, img: "/image/cart/muoiot.png"},
  { id: 708, category: "banh-keo", title: "Bánh Danisa", price: 150000, oldPrice: null, discount: null, rating: 3.9, img: "/image/cart/danisa.png"},
  { id: 709, category: "banh-keo", title: "Lays", price: 6000, oldPrice: null, discount: null, rating: 4.4, img: "/image/cart/lays.png"},
  { id: 710, category: "banh-keo", title: "Bánh gạo one one", price: 25000, oldPrice: null, discount: null, rating: 4.0, img: "/image/cart/banhgao.png"},
  { id: 711, category: "banh-keo", title: "Oshi snack đậu xanh nước dừa ", price: 13000, oldPrice: null, discount: null, rating: 4.5 , img: "/image/cart/snack.png"},
  { id: 712, category: "banh-keo", title: "Bánh con cá bống bang Orion", price: 12000, oldPrice: null, discount: null, rating: 4.9, img: "/image/cart/banhconca.png" },
  { id: 713, category: "banh-keo", title: "Bánh Custas cốm Orion", price: 30000, oldPrice: null, discount: null, rating: 4.0, img: "/image/cart/custas.png"},
  { id: 714, category: "banh-keo", title: "Kẹo Mentos", price: 15000, oldPrice: null, discount: "-10%", rating: 3.4, img: "/image/cart/mentos.png"},
  { id: 715, category: "banh-keo", title: "Kẹo socola <1kg>", price: 40000, oldPrice: null, discount: null, rating: 3.2, img: "/image/cart/keocan.png"},
   //8. ngũ côc
   { id: 801, category: "ngu-coc", title: "Ngũ cốc dinh dưỡng", price:80000, oldPrice: null, discount: null, rating: 4.9, img:"/image/cart/ngucoc.png"},
   { id: 802, category: "ngu-coc", title: "Gạo ST25",price: 250000, oldPrice: null, discount: null, rating: 4.9, img:"/image/cart/gao.png"},
  



];

